import { MongoClient } from "mongodb";

const uri = "mongodb+srv://gouseshaik99999_db_user:S0kT5yyS1fY3kxwL@cluster0.rspsosz.mongodb.net/mydb?retryWrites=true&w=majority"; // replace this
const client = new MongoClient(uri);

async function insertMovies() {
    try {
        await client.connect();
        const database = client.db("mydb"); // replace
        const collection = database.collection("movieslist");

        const movies = [
            {
                moviename: "Bahubali: The Beginning",
                language: "Telugu",
                directorName: "S.S. Rajamouli",
                poster: "https://www.themoviedb.org/t/p/w500/6lH6wFJTA9VuwlXbFfY5pXJj2pX.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2015,
                starring: "Prabhas, Rana Daggubati, Anushka Shetty",
                genres: "Action, Drama",
                categories: "Telugu Movies",
                country: "India",
                description: "An epic historical fiction about two warring brothers."
            },
            {
                moviename: "KGF Chapter 1",
                language: "Kannada",
                directorName: "Prashanth Neel",
                poster: "https://www.themoviedb.org/t/p/w500/q2oe0v8CGnQkhd2JL4XRovgGqB4.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2018,
                starring: "Yash, Srinidhi Shetty",
                genres: "Action, Thriller",
                categories: "Kannada Movies",
                country: "India",
                description: "The story of Rocky and his rise in the Kolar Gold Fields."
            },
            {
                moviename: "3 Idiots",
                language: "Hindi",
                directorName: "Rajkumar Hirani",
                poster: "https://www.themoviedb.org/t/p/w500/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2009,
                starring: "Aamir Khan, R. Madhavan, Sharman Joshi",
                genres: "Comedy, Drama",
                categories: "Hindi Movies",
                country: "India",
                description: "A story about friendship, love and life at an engineering college."
            },
            {
                moviename: "Drishyam",
                language: "Malayalam",
                directorName: "Jeethu Joseph",
                poster: "https://www.themoviedb.org/t/p/w500/9iKZyGfITnF8NLvY0aXqL4rxrDn.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2013,
                starring: "Mohanlal, Meena",
                genres: "Thriller, Drama",
                categories: "Malayalam Movies",
                country: "India",
                description: "A man tries to protect his family after a crime happens in their town."
            },
            {
                moviename: "RRR",
                language: "Telugu",
                directorName: "S.S. Rajamouli",
                poster: "https://www.themoviedb.org/t/p/w500/fgm8OZ7o4G2T8E1iGgdHPLdGSLI.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "N. T. Rama Rao Jr., Ram Charan",
                genres: "Action, Historical",
                categories: "Telugu Movies",
                country: "India",
                description: "Epic action drama set in pre-independence India."
            },
            {
                moviename: "Ponniyin Selvan",
                language: "Tamil",
                directorName: "Mani Ratnam",
                poster: "https://www.themoviedb.org/t/p/w500/6sCw2wbAPFOAwquq9xW6ZrDeU8A.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Vikram, Aishwarya Rai, Karthi",
                genres: "Historical, Drama",
                categories: "Tamil Movies",
                country: "India",
                description: "Epic historical story set in the Chola dynasty."
            },
            {
                moviename: "Bahubali 2: The Conclusion",
                language: "Telugu",
                directorName: "S.S. Rajamouli",
                poster: "https://www.themoviedb.org/t/p/w500/qmDpIHrmpJINaRKAfWQfftjCdyi.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2017,
                starring: "Prabhas, Anushka Shetty, Rana Daggubati",
                genres: "Action, Drama",
                categories: "Telugu Movies",
                country: "India",
                description: "The epic conclusion of the Bahubali saga."
            },
            {
                moviename: "Vikram",
                language: "Tamil",
                directorName: "Lokesh Kanagaraj",
                poster: "https://www.themoviedb.org/t/p/w500/pbqD4ta1u63hT3jO6sYzFvkZYZQ.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Kamal Haasan, Fahadh Faasil",
                genres: "Action, Thriller",
                categories: "Tamil Movies",
                country: "India",
                description: "High-octane action thriller."
            },
            {
                moviename: "Sita Ramam",
                language: "Telugu",
                directorName: "Hanu Raghavapudi",
                poster: "https://www.themoviedb.org/t/p/w500/gU3HnR4R93uEC0Qbsx6rQh3V2lJ.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Dulquer Salmaan, Mrunal Thakur",
                genres: "Romance, Drama",
                categories: "Telugu Movies",
                country: "India",
                description: "A love story across time and borders."
            },
            {
                moviename: "Pushpa: The Rise",
                language: "Telugu",
                directorName: "Sukumar",
                poster: "https://www.themoviedb.org/t/p/w500/6KOc0X4X9QnYixvQy2lXyC5T7jv.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2021,
                starring: "Allu Arjun, Rashmika Mandanna",
                genres: "Action, Drama",
                categories: "Telugu Movies",
                country: "India",
                description: "The rise of Pushpa Raj in the smuggling world."
            },
            {
                moviename: "Drishyam 2",
                language: "Malayalam",
                directorName: "Jeethu Joseph",
                poster: "https://www.themoviedb.org/t/p/w500/6m4ZQWgz4vY6L4kFwT0W6oY4v6A.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2021,
                starring: "Mohanlal, Meena",
                genres: "Thriller, Drama",
                categories: "Malayalam Movies",
                country: "India",
                description: "The suspense continues in the sequel to Drishyam."
            },
            {
                moviename: "RRR: Rise Again",
                language: "Hindi",
                directorName: "S.S. Rajamouli",
                poster: "https://www.themoviedb.org/t/p/w500/fkVdPNsjqR3m8H3t2s0J5w8iD.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Ram Charan, N. T. Rama Rao Jr.",
                genres: "Action, Historical",
                categories: "Hindi Movies",
                country: "India",
                description: "An alternate version of RRR for Hindi audiences."
            },
            {
                moviename: "Jai Bhim",
                language: "Tamil",
                directorName: "T.J. Gnanavel",
                poster: "https://www.themoviedb.org/t/p/w500/9C7s0V2ZWBJ8e5F5Fep9VJZIvO.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2021,
                starring: "Suriya, Manikandan",
                genres: "Drama, Crime",
                categories: "Tamil Movies",
                country: "India",
                description: "A courtroom drama highlighting social issues."
            },
            {
                moviename: "Spider-Man: No Way Home",
                language: "English",
                directorName: "Jon Watts",
                poster: "https://www.themoviedb.org/t/p/w500/uJYYizSuA9Y3DCs0qS4qWvHfZg4.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2021,
                starring: "Tom Holland, Zendaya",
                genres: "Action, Adventure",
                categories: "Hollywood Movies",
                country: "USA",
                description: "Peter Parker faces multiverse villains."
            },
            {
                moviename: "Avengers: Endgame",
                language: "English",
                directorName: "Anthony Russo, Joe Russo",
                poster: "https://www.themoviedb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2019,
                starring: "Robert Downey Jr., Chris Evans",
                genres: "Action, Sci-Fi",
                categories: "Hollywood Movies",
                country: "USA",
                description: "The Avengers assemble to defeat Thanos."
            },
            {
                moviename: "Master",
                language: "Tamil",
                directorName: "Lokesh Kanagaraj",
                poster: "https://www.themoviedb.org/t/p/w500/5N6nSQtWeS6N5B9Zft8OJpT7pv6.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2021,
                starring: "Vijay, Vijay Sethupathi",
                genres: "Action, Thriller",
                categories: "Tamil Movies",
                country: "India",
                description: "A teacher clashes with a criminal mastermind."
            },
            {
                moviename: "Sye Raa Narasimha Reddy",
                language: "Telugu",
                directorName: "Surender Reddy",
                poster: "https://www.themoviedb.org/t/p/w500/wNYJx8Y3mAKS3kVABvwvK4K7r1v.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2019,
                starring: "Chiranjeevi, Nayanthara",
                genres: "Action, Historical",
                categories: "Telugu Movies",
                country: "India",
                description: "Story of freedom fighter Uyyalawada Narasimha Reddy."
            },
            {
                moviename: "Eega",
                language: "Telugu",
                directorName: "S.S. Rajamouli",
                poster: "https://www.themoviedb.org/t/p/w500/qjHd5Fyt5vU3uT65X3NSW1vJxTR.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2012,
                starring: "Nani, Samantha Akkineni",
                genres: "Fantasy, Action",
                categories: "Telugu Movies",
                country: "India",
                description: "A man reincarnates as a housefly to take revenge."
            },
            {
                moviename: "Baahubali: The Lost Legend",
                language: "Telugu",
                directorName: "S.S. Rajamouli",
                poster: "https://www.themoviedb.org/t/p/w500/abcd1234fake.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2016,
                starring: "Prabhas, Rana Daggubati",
                genres: "Action, Drama",
                categories: "Telugu Movies",
                country: "India",
                description: "Adventure in the kingdom of Mahishmati."
            },
            {
                moviename: "Drishyam (Hindi)",
                language: "Hindi",
                directorName: "Nishikant Kamat",
                poster: "https://www.themoviedb.org/t/p/w500/fakeposter123.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2015,
                starring: "Ajay Devgn, Shriya Saran",
                genres: "Thriller, Drama",
                categories: "Hindi Movies",
                country: "India",
                description: "Hindi remake of Malayalam hit Drishyam."
            },
            {
                moviename: "RRR Telugu",
                language: "Telugu",
                directorName: "S.S. Rajamouli",
                poster: "https://www.themoviedb.org/t/p/w500/fakerrrtposter.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Ram Charan, Jr. NTR",
                genres: "Action, Drama",
                categories: "Telugu Movies",
                country: "India",
                description: "Telugu version of RRR."
            },
            {
                moviename: "Love Story",
                language: "Telugu",
                directorName: "Sekhar Kammula",
                poster: "https://www.themoviedb.org/t/p/w500/abcd1234lovestory.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2021,
                starring: "Naga Chaitanya, Sai Pallavi",
                genres: "Romance, Drama",
                categories: "Telugu Movies",
                country: "India",
                description: "A college love story full of emotions."
            },
            {
                moviename: "RRR Hindi",
                language: "Hindi",
                directorName: "S.S. Rajamouli",
                poster: "https://www.themoviedb.org/t/p/w500/fakerrrhindi.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Ram Charan, Jr. NTR",
                genres: "Action, Drama",
                categories: "Hindi Movies",
                country: "India",
                description: "Hindi dubbed version of RRR."
            },
            {
                moviename: "Gangubai Kathiawadi",
                language: "Hindi",
                directorName: "Sanjay Leela Bhansali",
                poster: "https://www.themoviedb.org/t/p/w500/abcdgangubai.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Alia Bhatt",
                genres: "Crime, Drama",
                categories: "Hindi Movies",
                country: "India",
                description: "The rise of a powerful woman in the underworld."
            },
            {
                moviename: "Vikram Vedha",
                language: "Tamil",
                directorName: "Pushkar-Gayathri",
                poster: "https://www.themoviedb.org/t/p/w500/vikramvedha.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2017,
                starring: "R. Madhavan, Vijay Sethupathi",
                genres: "Action, Thriller",
                categories: "Tamil Movies",
                country: "India",
                description: "A cop and a gangster face off in a thrilling cat-and-mouse game."
            },
            {
                moviename: "RRR Malayalam",
                language: "Malayalam",
                directorName: "S.S. Rajamouli",
                poster: "https://www.themoviedb.org/t/p/w500/fakerrrmalayalam.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Ram Charan, Jr. NTR",
                genres: "Action, Drama",
                categories: "Malayalam Movies",
                country: "India",
                description: "Malayalam dubbed version of RRR."
            },
            {
                moviename: "KGF Chapter 2",
                language: "Kannada",
                directorName: "Prashanth Neel",
                poster: "https://www.themoviedb.org/t/p/w500/kgf2.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Yash, Sanjay Dutt",
                genres: "Action, Thriller",
                categories: "Kannada Movies",
                country: "India",
                description: "Rocky returns to assert his dominance in the gold mines."
            },
            {
                moviename: "Eternals",
                language: "English",
                directorName: "Chloé Zhao",
                poster: "https://www.themoviedb.org/t/p/w500/eternals.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2021,
                starring: "Gemma Chan, Richard Madden",
                genres: "Action, Sci-Fi",
                categories: "Hollywood Movies",
                country: "USA",
                description: "Immortal beings protect humanity from ancient threats."
            },
            {
                moviename: "Doctor Strange in the Multiverse",
                language: "English",
                directorName: "Sam Raimi",
                poster: "https://www.themoviedb.org/t/p/w500/doctorstrange.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Benedict Cumberbatch, Elizabeth Olsen",
                genres: "Action, Fantasy",
                categories: "Hollywood Movies",
                country: "USA",
                description: "Dr. Strange explores alternate realities in the multiverse."
            },
            {
                moviename: "Pathaan",
                language: "Hindi",
                directorName: "Siddharth Anand",
                poster: "https://www.themoviedb.org/t/p/w500/pathaan.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2023,
                starring: "Shah Rukh Khan, Deepika Padukone",
                genres: "Action, Thriller",
                categories: "Hindi Movies",
                country: "India",
                description: "A RAW agent fights against international threats."
            },
            {
                moviename: "Vikram (Malayalam Dub)",
                language: "Malayalam",
                directorName: "Lokesh Kanagaraj",
                poster: "https://www.themoviedb.org/t/p/w500/vikrammalayalam.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Kamal Haasan, Fahadh Faasil",
                genres: "Action, Thriller",
                categories: "Malayalam Movies",
                country: "India",
                description: "Malayalam dubbed version of Tamil hit Vikram."
            },
            {
                moviename: "Pushpa 2",
                language: "Telugu",
                directorName: "Sukumar",
                poster: "https://www.themoviedb.org/t/p/w500/pushpa2.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2023,
                starring: "Allu Arjun, Rashmika Mandanna",
                genres: "Action, Drama",
                categories: "Telugu Movies",
                country: "India",
                description: "The next chapter in Pushpa Raj's rise."
            },
            {
                moviename: "RRR Tamil",
                language: "Tamil",
                directorName: "S.S. Rajamouli",
                poster: "https://www.themoviedb.org/t/p/w500/fakerrrtamil.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Ram Charan, N. T. Rama Rao Jr.",
                genres: "Action, Drama",
                categories: "Tamil Movies",
                country: "India",
                description: "Tamil dubbed version of RRR."
            },
            {
                moviename: "Pathaan Telugu",
                language: "Telugu",
                directorName: "Siddharth Anand",
                poster: "https://www.themoviedb.org/t/p/w500/pathaantelugu.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2023,
                starring: "Shah Rukh Khan, Deepika Padukone",
                genres: "Action, Thriller",
                categories: "Telugu Movies",
                country: "India",
                description: "Telugu dubbed version of Pathaan."
            },
            {
                moviename: "Jawan",
                language: "Hindi",
                directorName: "Atlee",
                poster: "https://www.themoviedb.org/t/p/w500/jawan.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2023,
                starring: "Shah Rukh Khan, Vijay Sethupathi",
                genres: "Action, Drama",
                categories: "Hindi Movies",
                country: "India",
                description: "A high-octane action thriller starring Shah Rukh Khan."
            },
            {
                moviename: "Spider-Man: Across the Spider-Verse",
                language: "English",
                directorName: "Joaquim Dos Santos",
                poster: "https://www.themoviedb.org/t/p/w500/spidermanacross.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2023,
                starring: "Shameik Moore, Hailee Steinfeld",
                genres: "Animation, Action",
                categories: "Hollywood Movies",
                country: "USA",
                description: "Miles Morales embarks on a new multiverse adventure."
            },
            {
                moviename: "Avatar: The Way of Water",
                language: "English",
                directorName: "James Cameron",
                poster: "https://www.themoviedb.org/t/p/w500/avatar2.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Sam Worthington, Zoe Saldaña",
                genres: "Action, Sci-Fi",
                categories: "Hollywood Movies",
                country: "USA",
                description: "The sequel to the legendary sci-fi adventure."
            },
            {
                moviename: "Beast",
                language: "Tamil",
                directorName: "Nelson Dilipkumar",
                poster: "https://www.themoviedb.org/t/p/w500/beast.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Vijay, Pooja Hegde",
                genres: "Action, Thriller",
                categories: "Tamil Movies",
                country: "India",
                description: "A thrilling action entertainer starring Vijay."
            },
            {
                moviename: "RRR English",
                language: "English",
                directorName: "S.S. Rajamouli",
                poster: "https://www.themoviedb.org/t/p/w500/fakerrrenglish.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Ram Charan, N. T. Rama Rao Jr.",
                genres: "Action, Drama",
                categories: "Hollywood Movies",
                country: "India",
                description: "English dubbed version of RRR."
            },
            {
                moviename: "Radhe Shyam",
                language: "Telugu",
                directorName: "Radha Krishna Kumar",
                poster: "https://www.themoviedb.org/t/p/w500/radheshyam.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Prabhas, Pooja Hegde",
                genres: "Romance, Drama",
                categories: "Telugu Movies",
                country: "India",
                description: "A period romantic drama with breathtaking visuals."
            }, {
                moviename: "Ponniyin Selvan",
                language: "Tamil",
                directorName: "Mani Ratnam",
                poster: "https://www.themoviedb.org/t/p/w500/ponniyinselvan.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Vikram, Karthi, Aishwarya Rai",
                genres: "Historical, Drama",
                categories: "Tamil Movies",
                country: "India",
                description: "Epic historical drama based on the famous novel."
            },
            {
                moviename: "Spider-Man: No Way Home",
                language: "English",
                directorName: "Jon Watts",
                poster: "https://www.themoviedb.org/t/p/w500/spiderman_nowayhome.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2021,
                starring: "Tom Holland, Zendaya",
                genres: "Action, Adventure",
                categories: "Hollywood Movies",
                country: "USA",
                description: "Spider-Man faces multiverse villains in an epic adventure."
            },
            {
                moviename: "Sita Ramam",
                language: "Telugu",
                directorName: "Hanu Raghavapudi",
                poster: "https://www.themoviedb.org/t/p/w500/sitaramam.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Dulquer Salmaan, Mrunal Thakur",
                genres: "Romance, Drama",
                categories: "Telugu Movies",
                country: "India",
                description: "A heartfelt romantic drama with beautiful storytelling."
            },
            {
                moviename: "Pushpa: The Rise",
                language: "Telugu",
                directorName: "Sukumar",
                poster: "https://www.themoviedb.org/t/p/w500/pushpa.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2021,
                starring: "Allu Arjun, Rashmika Mandanna",
                genres: "Action, Drama",
                categories: "Telugu Movies",
                country: "India",
                description: "Story of a red sandalwood smuggler and his rise."
            },
            {
                moviename: "RRR Kannada",
                language: "Kannada",
                directorName: "S.S. Rajamouli",
                poster: "https://www.themoviedb.org/t/p/w500/fakerrrkannada.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Ram Charan, N. T. Rama Rao Jr.",
                genres: "Action, Drama",
                categories: "Kannada Movies",
                country: "India",
                description: "Kannada dubbed version of RRR."
            },
            {
                moviename: "Vikram (Hindi Dub)",
                language: "Hindi",
                directorName: "Lokesh Kanagaraj",
                poster: "https://www.themoviedb.org/t/p/w500/vikramhindi.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Kamal Haasan, Fahadh Faasil",
                genres: "Action, Thriller",
                categories: "Hindi Movies",
                country: "India",
                description: "Hindi dubbed version of Tamil hit Vikram."
            },
            {
                moviename: "Doctor Strange 2",
                language: "English",
                directorName: "Sam Raimi",
                poster: "https://www.themoviedb.org/t/p/w500/doctorstrange2.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Benedict Cumberbatch, Elizabeth Olsen",
                genres: "Action, Fantasy",
                categories: "Hollywood Movies",
                country: "USA",
                description: "Exploring the multiverse of madness and alternate realities."
            },
            {
                moviename: "Avatar 2",
                language: "English",
                directorName: "James Cameron",
                poster: "https://www.themoviedb.org/t/p/w500/avatar2.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Sam Worthington, Zoe Saldaña",
                genres: "Action, Sci-Fi",
                categories: "Hollywood Movies",
                country: "USA",
                description: "The journey continues in Pandora's underwater world."
            },
            {
                moviename: "Black Panther: Wakanda Forever",
                language: "English",
                directorName: "Ryan Coogler",
                poster: "https://www.themoviedb.org/t/p/w500/blackpanther2.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Letitia Wright, Lupita Nyong'o",
                genres: "Action, Adventure",
                categories: "Hollywood Movies",
                country: "USA",
                description: "The legacy of Black Panther continues in Wakanda."
            },
            {
                moviename: "Beast",
                language: "Tamil",
                directorName: "Nelson Dilipkumar",
                poster: "https://www.themoviedb.org/t/p/w500/beast.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Vijay, Pooja Hegde",
                genres: "Action, Thriller",
                categories: "Tamil Movies",
                country: "India",
                description: "High-octane action with Vijay in the lead."
            },
            {
                moviename: "Pathaan Tamil",
                language: "Tamil",
                directorName: "Siddharth Anand",
                poster: "https://www.themoviedb.org/t/p/w500/pathaantamil.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2023,
                starring: "Shah Rukh Khan, Deepika Padukone",
                genres: "Action, Thriller",
                categories: "Tamil Movies",
                country: "India",
                description: "Tamil dubbed version of blockbuster Pathaan."
            },
            {
                moviename: "Jawan Telugu",
                language: "Telugu",
                directorName: "Atlee",
                poster: "https://www.themoviedb.org/t/p/w500/jawantelugu.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2023,
                starring: "Shah Rukh Khan, Vijay Sethupathi",
                genres: "Action, Drama",
                categories: "Telugu Movies",
                country: "India",
                description: "Telugu version of high-octane action Jawan."
            },
            {
                moviename: "Sonic the Hedgehog 2",
                language: "English",
                directorName: "Jeff Fowler",
                poster: "https://www.themoviedb.org/t/p/w500/sonic2.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Ben Schwartz, James Marsden",
                genres: "Animation, Adventure",
                categories: "Hollywood Movies",
                country: "USA",
                description: "Sonic returns for more fast-paced adventures."
            },
            {
                moviename: "The Batman",
                language: "English",
                directorName: "Matt Reeves",
                poster: "https://www.themoviedb.org/t/p/w500/thebatman.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Robert Pattinson, Zoë Kravitz",
                genres: "Action, Crime",
                categories: "Hollywood Movies",
                country: "USA",
                description: "Batman faces the dark underworld of Gotham City."
            },
            {
                moviename: "Thunivu",
                language: "Tamil",
                directorName: "H. Vinoth",
                poster: "https://www.themoviedb.org/t/p/w500/thunivu.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2023,
                starring: "Ajith Kumar",
                genres: "Action, Thriller",
                categories: "Tamil Movies",
                country: "India",
                description: "A stylish heist thriller starring Ajith Kumar."
            },
            {
                moviename: "Beast Telugu",
                language: "Telugu",
                directorName: "Nelson Dilipkumar",
                poster: "https://www.themoviedb.org/t/p/w500/beasttelugu.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Vijay, Pooja Hegde",
                genres: "Action, Thriller",
                categories: "Telugu Movies",
                country: "India",
                description: "Telugu version of high-octane action Beast."
            },
            {
                moviename: "Avatar: Way of Water Hindi",
                language: "Hindi",
                directorName: "James Cameron",
                poster: "https://www.themoviedb.org/t/p/w500/avatar2hindi.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Sam Worthington, Zoe Saldaña",
                genres: "Action, Sci-Fi",
                categories: "Hindi Movies",
                country: "USA",
                description: "Hindi dubbed version of Avatar 2."
            },
            {
                moviename: "KGF Chapter 1 Hindi",
                language: "Hindi",
                directorName: "Prashanth Neel",
                poster: "https://www.themoviedb.org/t/p/w500/kgf1hindi.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2018,
                starring: "Yash",
                genres: "Action, Drama",
                categories: "Hindi Movies",
                country: "India",
                description: "Hindi dubbed version of KGF Chapter 1."
            },
            {
                moviename: "KGF Chapter 1 Telugu",
                language: "Telugu",
                directorName: "Prashanth Neel",
                poster: "https://www.themoviedb.org/t/p/w500/kgf1telugu.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2018,
                starring: "Yash",
                genres: "Action, Drama",
                categories: "Telugu Movies",
                country: "India",
                description: "Telugu dubbed version of KGF Chapter 1."
            },
            {
                moviename: "RRR English 2",
                language: "English",
                directorName: "S.S. Rajamouli",
                poster: "https://www.themoviedb.org/t/p/w500/fakerrrenglish2.jpg",
                video: "https://res.cloudinary.com/dx6h8z8nz/video/upload/v1764954864/Telugu/pmrffrpzbd56g9n2gjwj.mp4",
                year: 2022,
                starring: "Ram Charan, N. T. Rama Rao Jr.",
                genres: "Action, Drama",
                categories: "Hollywood Movies",
                country: "India",
                description: "English dubbed version of RRR sequel."
            }
        ];




        const result = await collection.insertMany(movies);
        console.log(`${result.insertedCount} movies inserted!`);
    } finally {
        await client.close();
    }
}

insertMovies();
