import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import MuiRegistry from "./mui/MuiRegistry";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: '#24404b', color: '#d2f7f4' }} >
        <MuiRegistry>{children}</MuiRegistry>
      </body>
    </html>
  );
}
