name: CI-CD Pipeline

on:
  push:
    branches:
      - feat/health-check

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t gouseshaik7570/showtimeapp:latest .

      - name: Docker Scout Scan
        uses: docker/scout-action@v1
        with:
          command: quickview
          image: gouseshaik7570/showtimeapp:latest

      - name: Push Docker image
        run: |
          docker push gouseshaik7570/showtimeapp:latest
